/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.vista;

import jakarta.persistence.EntityManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.example.dao.UsuarioDAO;
import org.example.modelo.Usuario;
import org.example.utils.JPAUtils;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Christian
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
        cargarDatos();
    }
    
    private void cargarDatos() {
        EntityManager em = JPAUtils.getEntityManager();
        UsuarioDAO usuarioDAO = new UsuarioDAO(em);
        List<Usuario> usuarios = usuarioDAO.listAll();
        
        DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
        model.setRowCount(0);
        for (Usuario usuario : usuarios) {
            model.addRow(new Object[]{usuario.getId(), usuario.getUsuario(), usuario.getEmail(), usuario.getPassword(), usuario.getRecoveryCode()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menuCRUD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tablaPanel = new javax.swing.JPanel();
        emailTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        usuarioTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        borrarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        agregarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuCRUD.setBackground(new java.awt.Color(102, 0, 51));
        menuCRUD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LaTiendona - copia.png"))); // NOI18N
        menuCRUD.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 76));

        tablaPanel.setBackground(new java.awt.Color(102, 0, 51));
        tablaPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tablaPanelComponentAdded(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Correo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        javax.swing.GroupLayout tablaPanelLayout = new javax.swing.GroupLayout(tablaPanel);
        tablaPanel.setLayout(tablaPanelLayout);
        tablaPanelLayout.setHorizontalGroup(
            tablaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(tablaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(tablaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tablaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        tablaPanelLayout.setVerticalGroup(
            tablaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        menuCRUD.add(tablaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 320, 280));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        menuCRUD.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuCRUD.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 447, 110, 30));

        bg.add(menuCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 490));

        actualizarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualizarBtn.setText("ACTUALIZAR");
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });
        bg.add(actualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 120, 40));

        borrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrarBtn.setText("BORRAR");
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });
        bg.add(borrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 40));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "USUARIO", "CORREO", "PASSWORD", "RECOVERYCODE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);
        if (tablaUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios.getColumnModel().getColumn(4).setResizable(false);
        }

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 580, 360));

        agregarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarBtn.setText("GUARDAR");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        bg.add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tablaPanelComponentAdded

    }//GEN-LAST:event_tablaPanelComponentAdded

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        
        EntityManager em = JPAUtils.getEntityManager();
        UsuarioDAO usuarioDAO = new UsuarioDAO(em);
        
        String usuario = usuarioTxt.getText();
        String email = emailTxt.getText();
        String password = passwordTxt.getText();
        
        String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());
        
        Usuario nuevoUsuario = new Usuario(usuario, email, hashedPassword);
        
        try {
            usuarioDAO.save(nuevoUsuario);
            cargarDatos();
            JOptionPane.showMessageDialog(this, "Usuario agregado con éxito.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar usuario: " + e.getMessage());
        } finally {
            em.close();
        }
        

    }//GEN-LAST:event_agregarBtnActionPerformed

    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        EntityManager em = JPAUtils.getEntityManager();
        UsuarioDAO usuarioDAO = new UsuarioDAO(em);
        DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
        int fila = tablaUsuarios.getSelectedRow();
        
        if (fila >= 0) {
            Long id = (Long) model.getValueAt(fila, 0);
            Usuario usuario = usuarioDAO.findById(id);
            
            if (usuario != null) {
                usuario.setUsuario((String) tablaUsuarios.getValueAt(fila, 1));
                usuario.setEmail((String) tablaUsuarios.getValueAt(fila, 2));
                String hashedPassword = BCrypt.hashpw((String) tablaUsuarios.getValueAt(fila, 1), BCrypt.gensalt());
                usuario.setPassword(hashedPassword);
                
                try {
                    usuarioDAO.update(usuario);
                    
                    JOptionPane.showMessageDialog(this, "Usuario actualizado con éxito.");
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al actualizar usuario: " + e.getMessage());
                } finally {
                    cargarDatos();
                    em.close();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario para actualizar.");
        }
    }//GEN-LAST:event_actualizarBtnActionPerformed

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        EntityManager em = JPAUtils.getEntityManager();
        UsuarioDAO usuarioDAO = new UsuarioDAO(em);
        DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
        int fila = tablaUsuarios.getSelectedRow();
        
        if (fila >= 0) {
            Long id = (Long) model.getValueAt(fila, 0);
            try {
                usuarioDAO.delete(id);
                cargarDatos();
                JOptionPane.showMessageDialog(this, "Usuario borrado con éxito.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al borrar usuario: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario para borrar.");
        }

    }//GEN-LAST:event_borrarBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JButton borrarBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuCRUD;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JPanel tablaPanel;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
